---

- name: Create new EC2 Instance
  amazon.aws.ec2:
    key_name: cdoan-jenkins-key-2
    instance_type: m4.2xlarge
    image: ami-066df92ac6f03efca # RHEL 8.2
    wait: yes
    group: launch-wizard-1
    exact_count: 5
    vpc_subnet_id: subnet-817895db
    assign_public_ip: yes
    region: us-west-1
    volumes:
      - device_name: /dev/sda1
        volume_size: 100
        volume_type: gp2
        delete_on_termination: true
    user_data: |
      #!/bin/sh
      sudo dnf update -y ; sudo reboot
    instance_tags:
        Name: scale
        purpose: performance
    count_tag:
        Name: scale
        purpose: performance
  register: ec2

- name: Created instances
  debug:
    msg: 
      - "{{ ec2 }}"

# - name: dns names
#   debug:
#     msg: "{{ item.public_dns_name }}"
#   with_items: ec2.tagged_instances
