---

- name: shell
  shell: |
    curl -s http://169.254.169.254/latest/meta-data/public-hostname | cut -d'.' -f1
  register: output
  when: vm_provider == "aws"

- name: Set hostname_base for AWS VM
  set_fact:
    hostname_base: "{{ output.stdout }}"
  when: vm_provider == "aws"

- name: Set hostname_base for BM
  set_fact:
    hostname_base: "{{ inventory_hostname | regex_replace('[a-zA-Z]\\.(.*)', '') }}"
  when: vm_provider == "baremetal"


# - name: Set hostname_base
#   set_fact:
#     hostname_base: "{{ inventory_hostname | regex_replace('[a-zA-Z]\\.(.*)', '') }}"
  
- name: Set managed_cluster_name
  set_fact:
    managed_cluster_name: "{{ hostname_base }}-kind-{{ item }}"

- name: Debug managed cluster name
  debug:
    msg: "{{ managed_cluster_name }}"

- name: include rule
  include_role:
    name: rhacm_manage_cluster