---

- name: Create a specific count of EC2 Instance
  amazon.aws.ec2:
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    group: "{{ ec2_security_group }}"
    exact_count: "{{ ec2_instance_count }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    assign_public_ip: yes
    region: "{{ ec2_region }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ ec2_volume_size }}"
        volume_type: gp2
        delete_on_termination: true
    # user_data: |
    #   #!/bin/sh
    #   sudo dnf update -y ; sudo reboot
    instance_tags:
        Name: scale
        purpose: performance
    count_tag:
        Name: scale
        purpose: performance
  register: ec2

- name: Created instances
  debug:
    msg: 
      - "{{ ec2 }}"
