---

- name: Gather information about any VM instances named "scale"
  community.aws.ec2_instance_info:
    region: us-west-1
    filters:
      "tag:Name": scale
  register: ec2

- name: Log ec2 instance data
  debug:
    msg: "{{ item.public_dns_name }}"
  with_items: "{{ ec2.instances }}"
